CREATE TABLE `GROUPBASIC` (
	`ID` INT NOT NULL,
	`GROUPNAME` DOUBLE NOT NULL COMMENT '组份名称',
	`STORAGEMONEY` DOUBLE NOT NULL COMMENT '入库成本',
	`MOTIONVIS` DOUBLE NOT NULL COMMENT '运动粘度',
	`SULFURCON` DOUBLE NOT NULL COMMENT '硫含量',
	`NETHOT` DOUBLE NOT NULL COMMENT '净热值',
	`MOTIONTEMP` DOUBLE NOT NULL COMMENT '粘度温度',
	`OPTIME` TIMESTAMP NOT NULL
)
COMMENT='燃油组基础数据'
COLLATE='utf8_bin'
ENGINE=InnoDB
;

insert QRESULT(id,QUAGROUPNAME,FDNAME) values(1,'混合后密度','MIXINGDEN');/**混合后密度*/
insert QRESULT(id,QUAGROUPNAME,FDNAME) values(2,'混合后硫含量','MIXSULFURCONT');/**混合后密度*/
insert QRESULT(id,QUAGROUPNAME,FDNAME) values(3,'混合后粘度','VISCOSITY');/**混合后密度*/
insert QRESULT(id,QUAGROUPNAME,FDNAME) values(4,'混合后净热值','MIXHOT');/**混合后密度*/
